version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mychat-app
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=mychat
      - DB_USER=mychat
      - DB_PASS=moha1212

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mychat
      MYSQL_USER: mychat
      MYSQL_PASSWORD: moha1212
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  mysql_data: 